[build]
  functions = "netlify/functions"

[context.local]
  # Environment variables for local development
  [context.local.environment]
    NETLIFY_NEON_DATABASE_URL = "postgresql://neondb_owner:npg_WrKkpdj8Uns2@ep-calm-snow-a14go076-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
    NETLIFY_DATABASE_URL_UNPOOLED = "postgresql://neondb_owner:npg_WrKkpdj8Uns2@ep-calm-snow-a14go076.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
    NETLIFY_NEON_API_URL = "https://ep-calm-snow-a14go076.apirest.ap-southeast-1.aws.neon.tech/neondb/rest/v1"
    NETLIFY_NEON_API_KEY = "napi_azd8gp2876mvcgecuwp24hhhmuciqtzy3od4ge1up5n4uu0556jd30zc4ilwu2fl"
    NETLIFY_NEON_AUTH_URL = "https://ep-calm-snow-a14go076.neonauth.ap-southeast-1.aws.neon.tech/neondb/auth"
    NETLIFY_SECURE_JWT_SECRET = "MyneGCV+O8hzvWoznUTVqEhIT76t4RxsFZpu7iSHQl8="

[[redirects]]
  from = "/api/neon/*"
  to = "/.netlify/functions/neon/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/neon"
  to = "/.netlify/functions/neon"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[redirects]]
  from = "/api/db-admin/*"
  to = "/.netlify/functions/db-admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/db-admin"
  to = "/.netlify/functions/db-admin"
  status = 200
  force = true
