[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/neon/*"
  to = "/.netlify/functions/neon/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/neon"
  to = "/.netlify/functions/neon"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
  force = true
